import {
  barbershop,
  filmoteka,
  filmotekaTeamProject,
  iceCream,
  imageFinder,
  bigPhotoFromImageFinder,
  slimMom,
  webStudio,
  webStudioPortfolio,
  transitionFilmoteka,
  transitionFilmotekaTeamProject,
  tranitionIceCream,
  transitionSlimMom,
  transitionBarbershop,
} from "./projectImages";

export const projectData = [
  {
    id: 1,
    image: barbershop,
    transitionImage: transitionBarbershop,
    title: "Template for barbershop studio",
    codeLink: "https://github.com/Andrey1914/barbershop",
    liveLink: "https://barbershop-studio.netlify.app/",
  },
  {
    id: 2,
    image: filmotekaTeamProject,
    transitionImage: transitionFilmotekaTeamProject,
    title: "Movie search website",
    codeLink: "https://github.com/Andrey1914/filmoteka-project",
    liveLink: "https://indisputable09.github.io/filmoteka-project/",
  },
  {
    id: 3,
    image: iceCream,
    transitionImage: tranitionIceCream,
    title: "Online ice cream sale website template",
    codeLink: "https://github.com/Andrey1914/ice-cream",
    liveLink: "https://andrey1914.github.io/ice-cream/",
  },
  {
    id: 4,
    image: imageFinder,
    transitionImage: bigPhotoFromImageFinder,
    title: "Image search website",
    codeLink: "https://github.com/Andrey1914/goit-js-hw-11-infinite-scroll",
    liveLink: "https://andrey1914.github.io/goit-js-hw-11-infinite-scroll/",
  },
  {
    id: 5,
    image: slimMom,
    transitionImage: transitionSlimMom,
    title: "Website for weight management and diet",
    codeLink: "https://github.com/Andrey1914/slim-moms-frontend",
    liveLink: "https://andriibeha.github.io/slim-moms-frontend/",
  },
  {
    id: 6,
    image: webStudio,
    transitionImage: webStudioPortfolio,
    title: "Web studio website template",
    codeLink: "https://github.com/Andrey1914/goit-markup-hw-08",
    liveLink: "https://andrey1914.github.io/goit-markup-hw-08/",
  },
  {
    id: 7,
    image: filmoteka,
    transitionImage: transitionFilmoteka,
    title: "Movie search website",
    codeLink: "https://github.com/Andrey1914/goit-react-hw-05-movies",
    liveLink: "https://andrey1914.github.io/goit-react-hw-05-movies/",
  },
];
